### ISSUE TITLE
User can check balance on phone

### ISSUE THREAD

**Issue by Damiloju** [Sysmod-2021/bankappbackend#11]
## User story
> As a user, I want to have the ability to check my account balance on my phone.

## Acceptance criteria
> Given I'm a user and I have signed it
> When try to check my balance on my phone
> Then I should get feedback from the system with my balance details

## Technical requirements
- User account type must exist
- Balance object must exist
- Web client must exist

## Notes
I think is more of a compatibility issue. Normally users should be able to check their balance, so now we just have to provide a mobile-friendly web view or mobile app to make checking balance possible (which is already in the spec).

**Comment by Armin-Remenyi** [comment]
[https://github.com/Sysmod-2021/bankappbackend/issues/3](url)

**Comment by Armin-Remenyi** [comment]
#3
