### ISSUE TITLE
Sprint 1 - Account Creation

### ISSUE THREAD

**Issue by JonasBerx** [Sysmod-2021/bankappbackend#17]
# Account Creation : # 1

__Notice: Keep a personal log of your hours worked and progress on which tasks.__

Admin can create account. #5 

- [x] 0.5 SP : Account type ENUM
- [x] 2 SP : Bank-Account class + abstraction
- [x] 2 SP : Bank Class
- [x] 0.5 SP : Link User to bank (bidirectional)

##### Comments
- Abstraction between BankAccounts. 
- AdminBankAccount and UserBankAccount
- Accounts should keep username, password, balance (0 default), list of transactions done, list of transactions received, type ENUM
- Bank accounts are linked to Bank class
- Bank balance = accounts balance + bank extras

**Comment by iharsuvorau** [comment]
@hallibay, you can choose now your tasks from the list above and let me know, please, what you've taken, so I won't work on this

**Comment by hallibay** [comment]
Noted @iharsuvorau
