### ISSUE TITLE
Sequence diagrams

### ISSUE THREAD

**Issue by iharsuvorau** [Sysmod-2021/bankappbackend#26]
We need sequence diagrams for the whole app, including the front-end.

**Comment by MsAkiNom** [comment]
<kbd><img src="https://user-images.githubusercontent.com/77355484/142780226-e96e9a02-b26f-4135-9086-f5541c702797.png"> <kbd>

**Comment by iharsuvorau** [comment]
@MsAkiNom,

- it would be good to have an initial point visible like it's here https://en.wikipedia.org/wiki/Sequence_diagram#/media/File:CheckEmail.svg
- the part where we have "creates transaction" and "transaction type?", it's better to do the same way like with "Apply for account registration" and "validate details" with a self loop
- in the part where we have "funds OK" and "Transfer amount" and "funds sufficient" it seems like Backend found a direct communication channel to Admin :) it's possible, if we assume The Matrix is real 👀 But I think we should allow Admin to use only Frontend; you can re-arrange the diagram and put Admin next to Customer, both of them face only Frontend; if there're too many signals to show on one diagram, we can split it in two; please, review also other parts where Backend communicates with Admin

**Comment by iharsuvorau** [comment]
We're deciding to split it in several diagrams

- [ ] admin creates a user account
- [ ] customer makes a transfer
- [ ] admin revokes a transaction

**Comment by MsAkiNom** [comment]
Please, feel free to edit it, if needed
https://lucid.app/lucidchart/2ae9eac1-c1c9-498f-9b7b-2d3667f43f5d/edit?viewport_loc=-690%2C-533%2C5088%2C1898%2C0_0&invitationId=inv_a49b86a0-d5c6-4524-95c1-fc96a5d36a4d

Done for three tasks from the above checklist

![sequence_diagram](https://user-images.githubusercontent.com/77355484/143505171-ef1a734c-fadb-4a8f-92ba-9453eb27f07c.png)
