### ISSUE TITLE
Component diagram

### ISSUE THREAD

**Issue by iharsuvorau** [Sysmod-2021/bankappbackend#27]
We need an updated version of the component diagram based. The previous one is at https://github.com/Sysmod-2021/bankappbackend/issues/7#issuecomment-968110679

**Comment by huseynovramilx** [comment]
![demo_bank drawio](https://user-images.githubusercontent.com/52673837/142790792-05b6cccc-bd81-44a3-ae74-9a3a20c4205b.png)

**Comment by iharsuvorau** [comment]
Just to make it more clear, this was the previous attempt:

![](https://user-images.githubusercontent.com/6259054/141654493-fde60616-8d22-4978-95f7-5c3a77d3e4dd.png)

Regarding the recent changes, @huseynovramilx,

- usage of ports is not consistent: somewhere there are ports, somewhere there are no ports, somewhere nothing leads to a port from one side
- if we make a distinction between a component and subsystem, then we shouldn't mark a subsystem with a component icon; there's also a lonely component icon in WebServer near Customers, probably, we can just delete it
- I believe we shouldn't specify UI as an interface in WebApp, I'm not 100% sure though, I'd leave only code-related interfaces on this diagram; if you have other reasons, please, make them clear
- before we had Web Server as a separate component, but you're including the whole Bank inside Web Server. I believe it's still better to have Web Server only doing a very narrow part of the job and separate Bank from Web Server

**Comment by huseynovramilx** [comment]
![demo_bank_updated drawio (2)](https://user-images.githubusercontent.com/52673837/143036741-adffd7a0-8573-4264-a734-eb42a6baf20c.png)
Updated according to review,
Removed Users instead added Admins
Assumed that Admins will only be inserted manually to data store, hence "Get Admin", "Read Admins" instead of "Manage Admins", "Persist Admins"
