### ISSUE TITLE
Sprint 1 -  Perform transaction 

### ISSUE THREAD

**Issue by ira-halenok** [Sysmod-2021/bankappbackend#37]
# Perform transaction through the console: #14

__Notice: Keep a personal log of your hours worked and progress on which tasks.__

Performing transaction between two accounts in the system should be possible (through an API call). The person who executes the request shall enter the sender account ID, receiver account ID, transferred amount, and description.

- [x] 2.5 SP : changes to the WebConnector
- [X] 1 SP : Accounts is existed in the db (already implemented in Administrator class)
- [x] 0.5 SP : Reference amount and description (parameters in the API call)
- [x] 1 SP : Store in transaction log (bank, sender and received account)

##### Comments
After API calls for Administrators, add API calls for Customers.
Admin calls = between two users, bank -> user, user -> bank, seed.

**Comment by huseynovramilx** [comment]
Branch: [perform-transaction](https://github.com/Sysmod-2021/bankappbackend/tree/perform-transaction)
