### ISSUE TITLE
Login Logout

### ISSUE THREAD

**Issue by JonasBerx** [Sysmod-2021/bankappbackend#53]
# Login - Logout

__Notice: Keep a personal log of your hours worked and progress on which tasks.__

Any type of registered user should be able to log into the system and log out of the system.

- [x] [Story points] : Login api call
- [x] [Story points] : Logout api call
- [x] [Story points] : Set session in login -> ID + Type of user (Customer/Administrator)
- [x] [Story points] : Remove session on logout
- [x] [Story points] : Update api calls to check for session variables

**Comment by huseynovramilx** [comment]
[Work in progress](https://github.com/Sysmod-2021/bankappbackend/tree/auth/src/main/java)

**Comment by huseynovramilx** [comment]
#68
