### ISSUE TITLE
Account creation API

### ISSUE THREAD

**Issue by JonasBerx** [Sysmod-2021/bankappbackend#56]
# Account creation API

__Notice: Keep a personal log of your hours worked and progress on which tasks.__

Administrator should be able to create account through console (with params)

- [x] [Story points] : Add administrator api call to create customer account with parameters.

##### Comments

**Comment by joannamjc** [comment]
![image](https://user-images.githubusercontent.com/93998511/144075289-6425776a-dc59-44f8-a093-228267fe7cb9.png)
@JonasBerx Is this what my task entails?

**Comment by JonasBerx** [comment]
Was it already there? Because yes

**Comment by joannamjc** [comment]
No, I wrote it :))))
